### PR TITLE
Check converge

### PR DESCRIPTION
**Pull request by Chikuwaq**
### Why
nextnanopy.InputFile().execute() does not check if the simulation has converged. In most cases, it does not make sense to continue nextnanopy postprocessing if the simulation output is not reliable.

### What is changing
Added a convergence check routine for nn++, nn3 and nnNEGF. This can be activated by the option
nextnanopy.InputFile().execute(convergenceCheck=True).
Default is set to False for the moment. If the simulation has not converged, the user is asked whether he/she wants to continue running the Python script.

### Note
I added test script 'convergence_check.py' and corresponding nn3, nn++ and nnNEGF input files in \templates. These are only for testing purposes and may be deleted before merge.

### CODE REVIEW

**Comment by HeorhiiY** [comment]
In general, looks great! 
I have tried to run convergence_check.py for nnp, nn3 and negf. nnp and nn3 works fine, negf gives an error
```
E:\Anaconda\python.exe "E:/nextnano Users/heorhii.yehiazarian/nextnanopy/nextnanopy_package/nextnanopy/templates/convergence_check.py"
Traceback (most recent call last):
  File "E:/nextnano Users/heorhii.yehiazarian/nextnanopy/nextnanopy_package/nextnanopy/templates/convergence_check.py", line 20, in <module>
    my_input.execute(convergenceCheck=True)
  File "E:\nextnano Users\heorhii.yehiazarian\nextnanopy\nextnanopy_package\nextnanopy\nextnanopy\utils\misc.py", line 118, in f
    result = method(*args, **kwargs)
  File "E:\nextnano Users\heorhii.yehiazarian\nextnanopy\nextnanopy_package\nextnanopy\nextnanopy\inputs.py", line 273, in execute
    info = cmd_execute(**cmd_kwargs)
  File "E:\nextnano Users\heorhii.yehiazarian\nextnanopy\nextnanopy_package\nextnanopy\nextnanopy\commands.py", line 87, in execute
    os.chdir(wdir)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: ''
```
Is this expected? Do you have the same?

**Comment by Chikuwaq** [comment]
Thanks for testing. That issue hasn't happened to me so far. 
Do you have your NEGF executable in a special place? 

I cannot exclude the possibility that the option 'convergenceCheck=True' somehow interfered with kwargs for the execute methods (because I do not fully understand Python).
@brandonlokesy Can you also test it?

**Comment by Chikuwaq** [comment]
I added a check of executable path before running commands to make the error message more understandable. 

Also, I have polished the convergence check to give the user more meaningful error messages.

**Comment by HeorhiiY** [comment]
Nice! Now the error message with invalid executable looks better. I can merge it to master and and close the pull request.

**Pull request merged**
